on: [pull_request]
jobs:
  infracost:
    runs-on: your runner 
    env:
      working-directory: PATH/TO/TERRAFORM/CODE # Update this!

    name: Run Infracost
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false # This is recommended so the `terraform show` command outputs valid JSON

      # IMPORTANT: add any required steps here to set up cloud credentials so Terraform can run

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.working-directory }}

      - name: Terraform plan
        run: terraform plan -out tfplan.binary
        working-directory: ${{ env.working-directory }}

      - name: Terraform show
        run: terraform show -json tfplan.binary > plan.json
        working-directory: ${{ env.working-directory }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          
      - name: Generate Infracost JSON
        run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json
        working-directory: ${{ env.working-directory }}
        
      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          # Choose the commenting behavior, 'update' is a good default:
          behavior: update # Create a single comment and update it. The "quietest" option.                 
          # behavior: delete-and-new # Delete previous comments and create a new one.
          # behavior: hide-and-new # Minimize previous comments and create a new one.
          # behavior: new # Create a new cost estimate comment on every push.
